# Generated by Django 5.0 on 2025-12-26 17:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Project name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed project description')),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('archived', 'Archived')], default='planning', help_text='Current project status', max_length=20)),
                ('start_date', models.DateField(blank=True, help_text='Project start date', null=True)),
                ('deadline', models.DateField(blank=True, help_text='Project deadline', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tag name', max_length=50, unique=True)),
                ('color', models.CharField(default='#3B82F6', help_text='Hex color code (e.g., #3B82F6)', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name', max_length=100)),
                ('email', models.EmailField(help_text='Email address', max_length=254, unique=True)),
                ('role', models.CharField(choices=[('developer', 'Developer'), ('designer', 'Designer'), ('manager', 'Project Manager'), ('qa', 'QA Tester'), ('other', 'Other')], default='developer', help_text='Team member role', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Is this member currently active?')),
                ('joined_at', models.DateField(default=django.utils.timezone.now, help_text='Date joined the team')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Brief task description', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed task description')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', help_text='Task priority level', max_length=10)),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('review', 'In Review'), ('done', 'Done'), ('blocked', 'Blocked')], default='todo', help_text='Current task status', max_length=20)),
                ('estimated_hours', models.PositiveIntegerField(blank=True, help_text='Estimated hours to complete', null=True)),
                ('due_date', models.DateField(blank=True, help_text='Task due date', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When task was completed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(help_text='Project this task belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.project')),
                ('tags', models.ManyToManyField(blank=True, help_text='Tags for categorization', related_name='tasks', to='tasks.tag')),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Team member assigned to this task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='tasks.teammember')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'priority'], name='tasks_task_status_01b536_idx'), models.Index(fields=['project', 'status'], name='tasks_task_project_b78682_idx')],
            },
        ),
    ]
